# Site settings
title: Team-Stanton Blog
email: dstanton@mobiquityinc.com
description: > # this means to ignore newlines until "baseurl:"
  Team Stanton Blog!
baseurl: "/teamstanton" # the subpath of your site, e.g. /blog/
url: "http://mobiquity.github.io" # the base hostname & protocol for your site

twitter_username: gotoplanb
github_username:  gotoplanb

highlighter: pygments

exclude: [README.md, Gemfile, Gemfile.lock]

# Build settings
markdown: kramdown