# Site settings
title: Team-Stanton Blog
email: dstanton@mobiquityinc.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/teamstanton/" # the subpath of your site, e.g. /blog/
url: "http://mobiquity.github.io" # the base hostname & protocol for your site

twitter_username: gotoplanb
github_username:  gotoplanb

highlighter: pygments

exclude: [README.md, Gemfile, Gemfile.lock]

# Build settings
markdown: kramdown

authors:
  firoze:
    display_name: Firoze Rakib
    email: frakib@mobiquityinc.com
    twitter: frzrkb
    github: firoze
  gotoplanb:
    display_name: Dave Stanton
    email: dstanton@mobiquityinc.com
    twitter: gotoplanb
    github: gotoplanb
